### ISSUE TITLE
Issues With Scale from Zero at Azure with Modified Parameters Provided in Stencil

### ISSUE THREAD

**Issue by terzian-g** [gardener/autoscaler#145]
**What happened**:

Currently, trying to scale from zero for a landscape under AWS works fine, but the same behavior does not happen at Azure. The following: https://github.com/gardener/autoscaler/issues/27 was filed for support for scale from zero, for cases where the scale from zero should occur based on parameters provided in a stencil, rather than the hard-coded instance details (cpu, gpu, etc.). The reason for the need for the modified logic for the instance types is because the image that is booted (memoryone-chost) allows virtualization where the machine has 2-4x the total amount of DRAM.

As of now, adding the following into an AWS stencil allows bringing up a node in a landscape, with scale from zero, based on what's specified for the worker group, rather than the hard-coded instance details:

```
    machine:
      type: m5d.2xlarge
```

```
    providerConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: WorkerConfig
      dataVolumes:
        - name: chost
          snapshotID: snap-05baf98f2890417f9
      nodeTemplate:
        capacity:
          cpu: 8
          gpu: 0
          memory: 120Gi
```

With the above, scale up works fine.

But at Azure, the following stencil configuration changes does not allow bringing up a node in a landscape, with scale from zero, but rather reports:
`{"log":"Generating node template only using nodeTemplate from MachineClass shoot--hc-dev--i548674xa-haas-hana-s-vsmp-5e2ca-z3: template resources-\u003e cpu: 8,memory: 64Gi","pid":"1","severity":"INFO","source":"mcm_manager.go:673"}`

```
    machine:
      type: "Standard_L8s_v3"
```

```
    providerConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: WorkerConfig
      nodeTemplate:
        capacity:
          cpu: 8
          gpu: 0
          memory: 120Gi
```

**What you expected to happen**:

The provided "nodeTemplate:" configuration should be taken into consideration, with the Azure stencil, when scale from zero occurs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start an Azure stencil, modified with the above machine type and "providerConfig" section, using a memoryone-chost image. The "hc-dev-az-vsmp" stencil can be used, if available, with the above "providerConfig" section appended.
2. Try to cause a scale-up something (a HANA instance) that is larger than the DRAM of the machine, but less than the "memory: 120Gi".
3. You will receive errors, including the "Generating node template only using nodeTemplate from MachineClass..." error mentioned above.

**Anything else we need to know**:

**Environment**:
