### ISSUE TITLE
Autoscale issue in Multi zones in AliCloud

### ISSUE THREAD

**Issue by jia-jerry** [gardener/autoscaler#80]
**What would you like to be added**:

Currently, autoscaler doens't work as expected in AliCloud. If we have shoot with MZ and multiple groups, and there is a group and zone that has no node, then cluster auto scaling will fail. We expect autoscaler still work in this case.

e.g. 

```
    workers:
      - name: worker1
        machine:
          type: ecs.g6.large
          image:
            name: gardenlinux
            version: 184.0.0
        maximum: 4
        minimum: 2
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: cloud_efficiency
          size: 50Gi
        zones:
          - cn-shanghai-g
          - cn-shanghai-f
      - name: worker2
        machine:
          type: ecs.g6.xlarge
          image:
            name: gardenlinux
            version: 184.0.0
        maximum: 3
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: cloud_efficiency
          size: 50Gi
        zones:
          - cn-shanghai-g
          -  cn-shanghai-f

```

**Why is this needed**:
